### ISSUE TITLE
All the views should be consistent with navtabs and navbar

### ISSUE THREAD

**Issue by novakboskov** [UKS-2015/porter#32]
Some views use `project/navtabs.html` while some others use `show_navtabs` inclusion tag from `core/templatetags/show_navtabs.py`. I would remove `project/navtabs.html` and move on with this custom inclusion tag.

Also, there is inconsistency with navtabs - two tabs are marked as active at the same time.

**Comment by lazer-nikolic** [comment]
Check with Bojana if she fixed those locally.

**Comment by novakboskov** [comment]
@BojanaZ

**Comment by novakboskov** [comment]
`repository/list.html`
`repository/form.html`
`issue/list.html`
`issue/form.html`

are using desired custom inclusion tag after d6dd38641c2dd28f10beed1a003529ff379bc0e3

**Comment by BojanaZ** [comment]
It should be fixed in new commits.

**Comment by novakboskov** [comment]
Should I fix those or you currently working on it? @BojanaZ

**Comment by BojanaZ** [comment]
Currently working on it.

**Comment by novakboskov** [comment]
OK, ping me here when you're done with it so I can jack in `templates/common/delete_modal.html` into  member and milestone tabs to complete #28.

**Comment by BojanaZ** [comment]
This should be resolved now. @novakboskov, please check if everything regarding this issue is done.
