### ISSUE TITLE
Delete repository cares about core_comment table

### ISSUE THREAD

**Issue by novakboskov** [UKS-2015/porter#44]
Delete repository action yields an operational error

```
OperationalError at /porter/pop/repository/repo1/delete/
django.db.utils.OperationalError: no such table: core_comment
project/porter/porter/repository/views.py at line 138
```

**Comment by lazer-nikolic** [comment]
Can't reproduce. Have you tried migrating database to create the new table?

**Comment by novakboskov** [comment]
Yup, you're right. That was from your commit from last night and I didn't migrate since then.
This is not bug.
